# 文件名: 
# ---------------------
# 描述: 
#       2. (!!! 警告: 
# ---------------------

# ---------------------------------
# 1. 数据库连接池 (Databases)
# ---------------------------------
databases:
  # 生产环境数据主库 (来自原 db_server)
  prod_data_db:
    db_host: 
    db_port: 
    db_username: 
    db_password: 
    db_database: 
    ssh_host:
    ssh_username:
    ssh_password:

  # 生产环境监控库 (来自原 monitor_db_server)
  prod_monitor_db:
    db_host: 
    db_port: 
    db_username: 
    db_password: 
    db_database: 
    ssh_host:
    ssh_username:
    ssh_password:

  # 开发环境数据主库 (来自原 db_ssh_server)
  dev_data_db:
    db_host: 
    db_port: 
    db_username: 
    db_password: 
    db_database: 
    ssh_host: 
    ssh_username: 
    ssh_password: 

  # 开发环境监控库 (来自原 monitor_db_ssh_server)
  dev_monitor_db:
    db_host: 
    db_port: 
    db_username: 
    db_password: 
    db_database: 
    ssh_host: 
    ssh_username: 
    ssh_password: 

# ---------------------------------
# 2. OBS 存储池 (Object Storage)
# ---------------------------------
obs_storage:
  # 生产环境 OBS (来自原 detail/attachment_pro.yml)
  prod_obs:
    ak: 
    sk: 
    sv: 
    bt: 
    fd: 

  # 开发环境 OBS (来自原 detail/attachment_dev.yml)
  dev_obs:
    ak: 
    sk: 
    sv: 
    bt: 
    fd: 